name = "vpnrong"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"            # KV绑定名默认不可修改
id = "1f6345829ad341ad8067973ce7edcb16" # Production KV: 优选IP
